name: Telegram Proxy Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # اجرا هر 6 ساعت
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable unzip
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome version: $CHROME_VERSION"
        # استفاده از یک نسخه پایدار ChromeDriver
        CHROMEDRIVER_VERSION="138.0.7204.10"  # نسخه پایدار برای کروم 138
        echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget -q https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add proxy.txt README.md
        git commit -m "Update proxy.txt and README.md with latest proxies and timestamp" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
